wandb_version: 1

clients:
  value: adidas_28_clients
clients.CNN.lr:
  value: 0.000547174264329356
clients.n_estimators_client:
  value: 250
clients.num_iterations:
  value: 500
clients.xgb.max_depth:
  value: 7
dataset:
  value: adidas
use_wandb:
  value: true
