wandb_version: 1

clients:
  value: adidas_28_clients
clients.CNN.lr:
  value: 0.0002381375319327789
clients.n_estimators_client:
  value: 25
clients.num_iterations:
  value: 100
clients.xgb.max_depth:
  value: 4
dataset:
  value: adidas
use_wandb:
  value: true
