wandb_version: 1

clients:
  value: adidas_28_clients
clients.CNN.lr:
  value: 0.0008658424343421141
clients.n_estimators_client:
  value: 10
clients.num_iterations:
  value: 500
clients.xgb.max_depth:
  value: 4
dataset:
  value: adidas
use_wandb:
  value: true
