wandb_version: 1

clients:
  value: adidas_28_clients
clients.CNN.lr:
  value: 0.00024958666802185104
clients.n_estimators_client:
  value: 800
clients.num_iterations:
  value: 500
clients.xgb.max_depth:
  value: 4
dataset:
  value: adidas
use_wandb:
  value: true
