run-id = "retailer_region-cycling-ce-on-tf-0p2-le-10-eta-0p1-md-4-ss-1p0"
strategy = "cycling"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.2
local-epochs = 10

[params]
eta = 0.1
max_depth = 4
subsample = 1.0
