run-id = "retailer_region-bagging-ce-on-tf-0p3-le-1-eta-0p05-md-8-ss-1p0"
strategy = "bagging"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.3
local-epochs = 1

[params]
eta = 0.05
max_depth = 8
subsample = 1.0
