run-id = "retailer_region-cycling-ce-off-tf-0p2-le-1-eta-0p1-md-6-ss-0p8"
strategy = "cycling"
partitioner = "retailer_region"
centralised-eval = false
test-fraction = 0.2
local-epochs = 1

[params]
eta = 0.1
max_depth = 6
subsample = 0.8
