run-id = "retailer_region-bagging-ce-on-tf-0p2-le-15-eta-0p003-md-4-ss-0p6_2025-06-25"
strategy = "bagging"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.2
local-epochs = 15
scaled-lr = true

[params]
eta = 0.003
max_depth = 4
subsample = 0.6
