run-id = "retailer_region-bagging-ce-on-tf-0p3-le-1-eta-0p1-md-6-ss-1p0"
strategy = "bagging"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.3
local-epochs = 1

[params]
eta = 0.1
max_depth = 6
subsample = 1.0
