objective: reg:squarederror
eval_metric: rmse
# ───────── hiper-parámetros requeridos ─────────
n_estimators: 200          # número de árboles
learning_rate: 0.1
max_depth: 8
subsample: 1.0
colsample_bylevel: 1.0
colsample_bynode: 1.0
colsample_bytree: 1.0
alpha: 0.0
gamma: 0.0
num_parallel_tree: 1
min_child_weight: 1
enable_categorical: true
