wandb_version: 1

clients:
  value: cpusmall_5_clients
clients.CNN.lr:
  value: 0.0002985737065871784
clients.n_estimators_client:
  value: 25
clients.num_iterations:
  value: 100
clients.xgb.max_depth:
  value: 7
dataset:
  value:
  - cpusmall
use_wandb:
  value: true
